# Generated by Django 3.0.7 on 2020-06-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appScore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='screenshot',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
    ]
